kind: Deployment
apiVersion: apps/v1
metadata:
  name:  {{ .Release.Name }}-imagor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-imagor
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-imagor
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-imagor
        image: "{{ .Values.imagor.image.repository }}:{{ .Values.imagor.image.tag | default (include "defaultTag" .)  }}"
        imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
        {{- include "resources" .Values.imagor.resources | indent 8 }}
        ports:
        - containerPort: 8000
        env:
        - name: S3_FORCE_PATH_STYLE
          value: "1"
        - name: IMAGOR_CACHE_HEADER_TTL
          value: "168h"
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-imagor-secret-env
