name: Auto Approve after CodeRabbit

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: >
      github.event.review.state == 'approved' &&
      github.event.review.user.login == 'coderabbitai[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
