name: "frontend:test:build test docs"

on: push

jobs:
  # only (but most important) job from this workflow required for pull requests
  # check results serve as run conditions for all other jobs here
  files-changed:
    name: Detect File Changes - frontend-test-build-docs
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.frontend-test-build-docs }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.1.7

      - name: Check for frontend file changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  build:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build Docs - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.1.7

      - name: Frontend | Build Docs
        run: npm install && npm run docs:build
        working-directory: ${{env.WORKING_DIRECTORY}}